#config_version=6
mode:
  start_events: mode_horloge_started
  priority: 500

coil_player:
  # --- SENS HORAIRE ---
  s_horloge_encodeur_horaire:
    c_horloge_sens_anti_horaire:
      action: disable           # Coupe NET le sens inverse s'il tournait
    c_horloge_sens_horaire:
      action: pulse
      pulse_ms: 1500            # Le moteur reste alimenté pendant 1,5s pour accompagner l'aiguille
      power: 0.3

  # --- SENS ANTI-HORAIRE ---
  s_horloge_encodeur_anti_horaire:
    c_horloge_sens_horaire:
      action: disable           # Coupe NET le sens horaire s'il tournait
    c_horloge_sens_anti_horaire:
      action: pulse
      pulse_ms: 1500            # Le moteur reste alimenté pendant 1,5s dans l'autre sens
      power: 0.3