#config_version=6

sound_player:
  mode_attract_started:
    theme_bttf:
      bus: music
  mode_attract_display_loop_started:
    bttf_attract:
      bus: music
  mode_attract_game_over_started:
    bttf_theme:
      bus: music

slide_player:
  mode_attract_started:
    attract:
      target: DefaultDisplay