#config_version=6

# Base mode that starts at the beginning of each ball
# and stops at the end of each ball.

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

slide_player:
  mode_base_started:
    base_infos:
      target: DefaultDisplay

sound_player:
  mode_base_started:
    power_of_love:
      bus: music

mode_settings:
  game_ending:
    mode_start:
      - attract

# shows:
  # toy_hit:
    # - duration: 1s
      # events: open_mouth
    # - duration: 2s
      # events: close_mouth
show_player:
  # Événement déclenché lorsque le verrouillage des 3 billes est complet (ex: lancement du multibille)
  start_einstein_multiball:
    # 1. Le servo va directement à sa position maximale
    servo_bras_einstein: position_max_du_bras
    # 2. La vidéo est lancée en même temps
    einstein_multiball_video:
      action: play

# in your base mode (modes/base/config/base.yaml)
variable_player:
  # LES 3 PREMIERS SONT DES EXEMPLES AVEC POTATO A GARDER EN TETE
  # s_right_inlane_active:
    # score: 100
  # s_left_flipper_active:
    # score: 1000
    # potato: 1
  # s_right_flipper_active:
    # potato: -2
  s_left_flipper_active:
    score: 100
  s_right_flipper_active:
    score: 100
  # s_start:
    # number: 0-0-3
    # tags: start
  s_left_slingshot_active:
    score: 100
  s_right_slingshot_active:
    score: 100
  s_lower_jet_active:
    score: 500
  s_left_jet_active:
    score: 100
  s_right_jet_active:
    score: 100
  s_left_popper_active:
    score: 100
  s_right_popper_active:
    score: 100
  # s_top_popper_active:
    # score: 100
  # OPTOS
  s_ramp_1985_entree_active:
    score: 100
  s_ramp_hotel_de_ville_active:
    score: 100
  s_ramp_2015_lower_active:
    score: 100
  s_ramp_marty_lower_active:
    score: 100
  s_ramp_george_active:
    score: 100
  s_ramp_bttf_active:
    score: 100
  s_left_inlane_active:
    score: 100
  s_left_outlane_active:
    score: 100
  s_target_plutonium_active:
    score: 100
  s_1955_lane_active:
    score: 100
  s_bank_dmc_lower_active:
    score: 100
  s_bank_dmc_middle_active:
    score: 100
  s_bank_dmc_upper_active:
    score: 100
  s_entree_souterrain_active:
    score: 100
  s_trough1_active:
    score: 100
  s_trough2_active:
    score: 100
  s_trough3_active:
    score: 100
  s_trough4_active:
    score: 100
  s_right_outlane_active:
    score: 100
  s_right_inlane_active:
    score: 100
  s_ramp_1955_active:
    score: 100
  s_ramp_1985_sortie_active:
    score: 100
  s_lane_1885_active:
    score: 100
  s_target_hill_valley_active:
    score: 100
  s_lane_cafe_einstein_active:
    score: 100
  s_lane_einstein_upper_active:
    score: 100
  s_bras_slot1_active:
    score: 100
  s_bras_slot2_active:
    score: 100
  s_bras_slot3_active:
    score: 100
  s_spinner_almanach_active:
    spinner_rotations: 1
    score: 100
  s_lane_biff_active:
    score: 100
  s_lane_doc_lower_active:
    score: 100
  s_lane_doc_upper_active:
    score: 100
  s_lane_horloge_active:
    score: 100
  s_target_foudre_active:
    score: 100
  s_target_overboard_active:
    score: 100
  s_bank_doc_lower_active:
    score: 100
  s_bank_doc_middle_active:
    score: 100
  s_bank_doc_upper_active:
    score: 100
  s_ramp_2015_upper_active:
    score: 100
  s_lane_marty_lower_active:
    score: 100
  s_lane_marty_upper_active:
    score: 100
  s_ramp_marty_upper_active:
    score: 100
  s_spinner_pierre_cardin_active:
    spinner_rotations: 1
    score: 100
  s_lane_lorraine_active:
    score: 100
  s_lane_marvin_active:
    score: 100
  s_lane_guitar_active:
    score: 100
  # s_tilt:
    # number: 1-0-80
    
sequence_shots:
  shot_ramp_1985:
    switch_sequence: s_ramp_1985_entree, s_ramp_1985_sortie
    sequence_timeout: 3s
  shot_ramp_2015:
    switch_sequence: s_ramp_2015_lower, s_ramp_2015_upper
    sequence_timeout: 3s
  shot_ramp_marty:
    switch_sequence: s_ramp_marty_lower, s_ramp_marty_upper
    sequence_timeout: 3s
    # QUE FAIRE DE   s_lane_marty_lower ET s_lane_marty_upper
  # QUE FAIRE DE s_ramp_hotel_de_ville ET s_ramp_george ET s_ramp_bttf CAR IL N'Y A PAS DE SORTIE, IL FAUT LE COMBINER AVEC UN AUTRE SWITCH ??
  # IDEM POUR s_ramp_bttf ET s_lane_cafe_einstein ET s_lane_einstein_upper
  shot_ramp_1955:
    switch_sequence: s_lane_1955, s_ramp_1955
    sequence_timeout: 3s
  # REVOIR SEQUENCE TIMEOUT A 1S POUR LES RAMPES DE BAS DE PLATEAU
  
shots:
  shot_shoot_again:
    switches: s_left_outlane, s_right_outlane
    show_tokens:
      leds: l_insert_shoot_again
  shot_left_inlane:
    switches: s_left_inlane
    show_tokens:
      leds: l_insert_left_inlane
  shot_left_outlane:
    switches: s_left_outlane
    show_tokens:
      leds: l_insert_left_outlane
  shot_right_inlane:
    switches: s_right_inlane
    show_tokens:
      leds: l_insert_right_inlane
  shot_right_outlane:
    switches: s_right_outlane
    show_tokens:
      leds: l_insert_right_outlane
  # shot_1885:
    # switches: s_left_popper
    # show_tokens:
      # leds: l_insert_1885
  # shot_1955:
    # switches: s_left_popper
    # show_tokens:
      # leds: l_insert_1955
  # shot_1985:
    # switches: s_left_popper
    # show_tokens:
      # leds: l_insert_1985
  # shot_2015:
    # switches: s_left_popper
    # show_tokens:
      # leds: l_insert_2015
  # shot_biff:
    # switches: s_left_popper
    # show_tokens:
      # leds: l_insert_biff
  # shot_bttf:
    # switches: s_left_popper
    # show_tokens:
      # leds: l_insert_bttf
  # shot_x2:
    # switches: 
    # show_tokens:
      # leds: l_insert_x2
  # shot_extraball:
    # switches: 
    # show_tokens:
      # leds: l_insert_extraball
  shot_ramp_hotel_de_ville:
    switches: s_ramp_hotel_de_ville
    show_tokens:
      leds: l_insert_ramp_hotel_de_ville
  shot_ramp_george:
    switches: s_ramp_george
    show_tokens:
      leds: l_insert_ramp_george
  shot_ramp_bttf:
    switches: s_ramp_bttf
    show_tokens:
      leds: l_insert_ramp_bttf
  shot_target_plutonium:
    switches: s_target_plutonium
    show_tokens:
      leds: l_insert_target_plutonium
  # shot_lane_1955:
    # switches: s_lane_1955
    # show_tokens:
      # leds: l_insert_lane_1955
  shot_bank_dmc_lower:
    switches: s_bank_dmc_lower
    show_tokens:
      leds: l_insert_bank_dmc_lower
  shot_bank_dmc_middle:
    switches: s_bank_dmc_middle
    show_tokens:
      leds: l_insert_bank_dmc_middle
  shot_bank_dmc_upper:
    switches: s_bank_dmc_upper
    show_tokens:
      leds: l_insert_bank_dmc_upper
  shot_entree_souterrain:
    switches: s_entree_souterrain
    show_tokens:
      leds: l_insert_entree_souterrain
  shot_ramp_1955:
    switches: s_ramp_1955
    show_tokens:
      leds: l_insert_ramp_1955
  shot_lane_1885:
    switches: s_lane_1885
    show_tokens:
      leds: l_insert_lane_1885
  shot_target_hill_valley:
    switches: s_target_hill_valley
    show_tokens:
      leds: l_insert_target_hill_valley
  shot_lane_cafe_einstein:
    switches: s_lane_cafe_einstein
    show_tokens:
      leds: l_insert_lane_cafe_einstein
  shot_lane_einstein_upper:
    switches: s_lane_einstein_upper
    show_tokens:
      leds: l_insert_lane_einstein_upper
  shot_mode_einstein_multiball:
    switches: s_top_popper
    show_tokens:
      leds: l_insert_einstein_multiball
  shot_lane_biff:
    switches: s_lane_biff
    show_tokens:
      leds: l_insert_lane_biff
  # ?????
  # shot_lane_doc_lower:
    # switches: s_lane_doc_lower
    # show_tokens:
      # leds: l_insert_lane_doc_lower
  # shot_lane_doc_upper:
    # switches: s_lane_doc_upper
    # show_tokens:
      # leds: l_insert_lane_doc_upper
  shot_lane_horloge:
    switches: s_lane_horloge
    show_tokens:
      leds: l_insert_lane_horloge
  shot_target_foudre:
    switches: s_target_foudre
    show_tokens:
      leds: l_insert_target_foudre
  shot_target_overboard:
    switches: s_target_overboard
    show_tokens:
      leds: l_insert_target_overboard
  shot_bank_doc_lower:
    switches: s_bank_doc_lower
    show_tokens:
      leds: l_insert_bank_doc_lower
  shot_bank_doc_middle:
    switches: s_bank_doc_middle
    show_tokens:
      leds: l_insert_bank_doc_middle
  shot_bank_doc_upper:
    switches: s_bank_doc_upper
    show_tokens:
      leds: l_insert_bank_doc_upper
  shot_ramp_2015_upper:
    switches: s_ramp_2015_upper
    show_tokens:
      leds: l_insert_ramp_2015_upper
  shot_lane_marty:
    switches: s_lane_marty
    show_tokens:
      leds: l_insert_lane_marty
  shot_lane_lorraine:
    switches: s_lane_lorraine
    show_tokens:
      leds: l_insert_lane_lorraine
  shot_lane_marvin:
    switches: s_lane_marvin
    show_tokens:
      leds: l_insert_lane_marvin
  shot_lane_guitar:
    switches: s_lane_guitar
    show_tokens:
      leds: l_insert_lane_guitar_1, l_insert_lane_guitar_2, l_insert_lane_guitar_3, l_insert_lane_guitar_4, l_insert_lane_guitar_5, l_insert_lane_guitar_6, l_insert_lane_guitar_7, l_insert_lane_guitar_8, l_insert_lane_guitar_9, l_insert_lane_guitar_10
  
  shot_ramp_1985_complete:
    hit_events: shot_ramp_1985_hit
    show_tokens:
      leds: l_ramp_1985_entree
      # A REVOIR PK ENTREE ???
  shot_ramp_2015_complete:
    hit_events: shot_ramp_2015_hit
    show_tokens:
      leds: l_insert_ramp_2015_upper
  shot_ramp_1955_complete:
    hit_events: shot_ramp_1955_hit
    show_tokens:
      leds: l_insert_ramp_1955

shot_groups:
  qualification_selection_modes_group:
    shots: shot_lane_1885, shot_ramp_1955_complete, shot_ramp_1985_complete, shot_ramp_2015_complete, shot_lane_biff, shot_ramp_bttf
    enable_events: ball_started
    reset_events: selection_modes_completed
      
# PENSER A FAIRE ETTEINDRE LES BUMPERS TEMPORAIREMENT LORSQU'ILS SONT TOUCHES