#config_version=6

# Base mode that starts at the beginning of each ball
# and stops at the end of each ball.

mode:
  start_events: ball_starting
  stop_events: ball_will_end
  priority: 100

slide_player:
  mode_base_started:
    base_infos:
      target: DefaultDisplay

sound_player:
  mode_base_started:
    power_of_love:
      bus: music

# we will initially set the value to 0 when the machine starts up
player_vars:
  potato:
    initial_value: 0

# in your base mode (modes/base/config/base.yaml)
variable_player:
  # LES 3 PREMIERS SONT DES EXEMPLES AVEC POTATO A GARDER EN TETE
  # s_right_inlane_active:
    # score: 100
  # s_left_flipper_active:
    # score: 1000
    # potato: 1
  # s_right_flipper_active:
    # potato: -2
  s_left_flipper_active:
    score: 100
  s_right_flipper_active:
    score: 100
  # s_start:
    # number: 0-0-3
    # tags: start
  s_left_slingshot_active:
    score: 100
  s_right_slingshot_active:
    score: 100
  s_lower_jet_active:
    score: 500
  s_left_jet_active:
    score: 100
  s_right_jet_active:
    score: 100
  s_left_popper_active:
    score: 100
  s_right_popper_active:
    score: 100
  # s_top_popper_active:
    # score: 100
  # OPTOS
  s_ramp_1985_entree_active:
    score: 100
  s_ramp_hotel_de_ville_active:
    score: 100
  s_ramp_2015_lower_active:
    score: 100
  s_ramp_marty_lower_active:
    score: 100
  s_ramp_george_active:
    score: 100
  s_ramp_bttf_active:
    score: 100
  s_left_inlane_active:
    score: 100
  s_left_outlane_active:
    score: 100
  s_target_plutonium_active:
    score: 100
  s_1955_lane_active:
    score: 100
  s_bank_dmc_lower_active:
    score: 100
  s_bank_dmc_middle_active:
    score: 100
  s_bank_dmc_upper_active:
    score: 100
  s_entree_souterrain_active:
    score: 100
  s_trough1_active:
    score: 100
  s_trough2_active:
    score: 100
  s_trough3_active:
    score: 100
  s_trough4_active:
    score: 100
  s_right_outlane_active:
    score: 100
  s_right_inlane_active:
    score: 100
  s_ramp_1955_active:
    score: 100
  s_ramp_1985_sortie_active:
    score: 100
  s_lane_1885_active:
    score: 100
  s_target_hill_valley_active:
    score: 100
  s_lane_cafe_einstein_active:
    score: 100
  s_lane_einstein_upper_active:
    score: 100
  s_bras_slot1_active:
    score: 100
  s_bras_slot2_active:
    score: 100
  s_bras_slot3_active:
    score: 100
  s_spinner_almanach_active:
    score: 100
  s_lane_biff_active:
    score: 100
  s_lane_doc_lower_active:
    score: 100
  s_lane_doc_upper_active:
    score: 100
  s_lane_horloge_active:
    score: 100
  s_target_foudre_active:
    score: 100
  s_target_overboard_active:
    score: 100
  s_bank_doc_lower_active:
    score: 100
  s_bank_doc_middle_active:
    score: 100
  s_bank_doc_upper_active:
    score: 100
  s_ramp_2015_upper_active:
    score: 100
  s_lane_marty_lower_active:
    score: 100
  s_lane_marty_upper_active:
    score: 100
  s_ramp_marty_upper_active:
    score: 100
  s_spinner_lorraine_active:
    score: 100
  s_lane_lorraine_active:
    score: 100
    s_lane_marvin_active:
    score: 100
  s_lane_guitar_active:
    score: 100
  # s_tilt:
    # number: 1-0-80