#config_version=6

mode:
  start_events: ball_started   # Le mode s'allume dès qu'une bille est en jeu
  priority: 500                # Priorité moyenne pour ce mode de jeu

# 1. On configure le déviateur pour qu'il obéisse à ce mode
diverters:
  deviateur_rampe_bras:
    activation_coil: c_deviateur_bras_actuate
    type: pulse
    duration: 30ms
    feeder_device: playfield
    targets: bd_upper_vuk
    # Le déviateur s'active AUTOMATIQUEMENT dès que MPF demande à verrouiller une bille !
    activate_events: ball_lock_bd_bras_rotatif_einstein_enabled
    disable_events: ball_lock_bd_bras_rotatif_einstein_disabled

# 2. Le contrôle du servo pour la rotation du bras
servo_controllers:
  controleur_bras_einstein:
    servo: servo_bras_einstein
    control_events:
      - event: start_multiball_einstein
        position: ejection_multiball
      - event: multiball_einstein_ended
        position: attente_chargement

# 3. On configure la logique du Lock (verrouillage) pour ce mode
ball_locks:
  bd_bras_rotatif_einstein:
    ball_device: bd_bras_rotatif
    balls_to_lock: 3
    lock_events: ball_started
    # Quand le lock est plein, il déclenche la multibille :
    full_events: start_multiball_einstein

# 4. On configure la Multibille qui va s'activer une fois le bras plein
multiballs:
  multiball_einstein:
    ball_count: 3
    ball_locks: bd_bras_rotatif
    start_events: start_multiball_einstein

    # end_events: end_multiball_einstein ????