#config_version=6

mode:
  start_events: ball_started
  priority: 500

# 1. Compteur de tirs standard
counters:
  compteur_tirs_einstein:
    count_events: s_lane_cafe_einstein_active
    count_complete_value: 3
    events_when_complete: einstein_palier_atteint
    persist_state: true
    reset_on_complete: true

# 2. Gestion dynamique de la progression des paliers et des actions de sécurité
event_player:
  einstein_palier_atteint{device.counters.compteur_tirs_einstein.value == 3}:
    - activer_deviateur_einstein
  einstein_palier_atteint{device.counters.compteur_tirs_einstein.value == 6}:
    - activer_deviateur_einstein
  einstein_palier_atteint{device.counters.compteur_tirs_einstein.value == 9}:
    - activer_deviateur_einstein
  einstein_palier_atteint{device.counters.compteur_tirs_einstein.value == 12}:
    - activer_deviateur_einstein
  
  # Sécurités du déviateur déplacées ici sous forme d'événements standards
  multiball_lock_lock_einstein_full: desactiver_deviateur_bras
  mode_multiball_einstein_started: desactiver_deviateur_bras

# 3. Logique de verrouillage physique pour les 3 slots
multiball_locks:
  lock_einstein:
    lock_devices: bd_bras_rotatif
    balls_to_lock: 3                            

# 4. Déclenchement de la multibille à 3 billes
multiballs:
  multiball_einstein:
    ball_count: 3
    ball_locks: bd_bras_rotatif                 
    start_events: multiball_lock_lock_einstein_full