#config_version=6

## MPF Main Machine Config File

modes:
  - attract
  - base
  - einstein_multiball

hardware:
  platform: opp
  driverboards: cobrapin

opp:
  ports:
    - /dev/tty.usbmodem568441744C001
    - /dev/tty.usbmodem5683416F4C001

displays:
  DefaultDisplay:
    width: 1920
    height: 1080
    fps: 75

psus:
  default:
    release_wait_ms: 50

switches:
  s_left_flipper:
    number: 0-0-1
    tags: left_flipper
  s_right_flipper:
    number: 0-0-2
    tags: right_flipper
  s_start:
    number: 0-0-3
    tags: start
  s_trough5:
    number: 0-0-8
  s_trough_jam:
    number: 0-0-9
    type: NC
  s_plunger:
    number: 0-0-10
  # SERVO
  s_servo_bras_einstein:
    number: 0-0-11
  s_left_slingshot:
    number: 0-0-27
  s_right_slingshot:
    number: 0-0-26
  s_lower_jet:
    number: 0-0-25
  s_left_jet:
    number: 0-0-24
  s_right_jet:
    number: 0-0-19
  s_left_popper:
    number: 0-0-18
  s_right_popper:
    number: 0-0-17
  s_top_popper:
    number: 0-0-16
  # OPTOS
  s_ramp_1985_entree:
    number: 0-0-1
    type: NC
  s_ramp_hotel_de_ville:
    number: 1-0-2
    type: NC
  s_horloge:
    number: 1-0-3
    type: NC
  s_ramp_2015_lower:
    number: 1-0-8
    type: NC
  s_ramp_marty_lower:
    number: 1-0-9
    type: NC
  s_ramp_george:
    number: 1-0-10
    type: NC
  s_ramp_bttf:
    number: 1-0-11
    type: NC
  s_left_inlane:
    number: 1-0-32
    tags: playfield_active
  s_left_outlane:
    number: 1-0-33
    tags: playfield_active
  s_target_plutonium:
    number: 1-0-34
    debounce: quick
    #ignore_window_ms: 2ms
    tags: playfield_active
  s_1955_lane:
    number: 1-0-35
    tags: playfield_active
  s_bank_dmc_lower:
    number: 1-0-36
    debounce: quick
    #ignore_window_ms: 2ms
    tags: playfield_active
  s_bank_dmc_middle:
    number: 1-0-37
    debounce: quick
    #ignore_window_ms: 2ms
    tags: playfield_active
  s_bank_dmc_upper:
    number: 1-0-38
    debounce: quick
    #ignore_window_ms: 2ms
    tags: playfield_active
  s_entree_souterrain:
    number: 1-0-39
    tags: playfield_active
  s_trough1:
    number: 1-0-40
  s_trough2:
    number: 1-0-41
  s_trough3:
    number: 1-0-42
  s_trough4:
    number: 1-0-43
  s_right_outlane:
    number: 1-0-44
    tags: playfield_active
  s_right_inlane:
    number: 1-0-45
    tags: playfield_active
  s_ramp_1955:
    number: 1-0-46
    tags: playfield_active
  s_ramp_1985_sortie:
    number: 1-0-47
    tags: playfield_active
  s_lane_1885:
    number: 1-0-48
    tags: playfield_active
  s_target_hill_valley:
    number: 1-0-49
    debounce: quick
    #ignore_window_ms: 2ms
    tags: playfield_active
  s_lane_cafe_einstein:
    number: 1-0-50
    tags: playfield_active
  s_lane_einstein_upper:
    number: 1-0-51
    tags: playfield_active
  s_bras_slot1:
    number: 1-0-52
  s_bras_slot2:
    number: 1-0-53
  s_bras_slot3:
    number: 1-0-54
  s_spinner_almanach:
    number: 1-0-56
    tags: playfield_active
  s_lane_biff:
    number: 1-0-57
    tags: playfield_active
  s_lane_doc_lower:
    number: 1-0-58
    tags: playfield_active
  s_lane_doc_upper:
    number: 1-0-59
    tags: playfield_active
  s_lane_horloge:
    number: 1-0-60
    tags: playfield_active
  s_target_foudre:
    number: 1-0-61
    debounce: quick
    #ignore_window_ms: 2ms
    tags: playfield_active
  s_target_overboard:
    number: 1-0-64
    debounce: quick
    #ignore_window_ms: 2ms
    tags: playfield_active
  s_bank_doc_lower:
    number: 1-0-65
    debounce: quick
    #ignore_window_ms: 2ms
    tags: playfield_active
  s_bank_doc_middle:
    number: 1-0-66
    debounce: quick
    #ignore_window_ms: 2ms
    tags: playfield_active
  s_bank_doc_upper:
    number: 1-0-67
    debounce: quick
    #ignore_window_ms: 2ms
    tags: playfield_active
  s_ramp_2015_upper:
    number: 1-0-68
    tags: playfield_active
  s_lane_marty_lower:
    number: 1-0-72
    tags: playfield_active
  s_lane_marty_upper:
    number: 1-0-73
    tags: playfield_active
  s_ramp_marty_upper:
    number: 1-0-74
    tags: playfield_active
  s_spinner_pierre_cardin:
    number: 1-0-75
    tags: playfield_active
  s_lane_lorraine:
    number: 1-0-76
    tags: playfield_active
  s_lane_marvin:
    number: 1-0-77
    tags: playfield_active
  s_lane_guitar:
    number: 1-0-78
    tags: playfield_active
  s_tilt:
    number: 1-0-80
  s_launch_button:
    number: 1-0-81
  # MANQUE LE CAPTEUR DE PORTE ET L'ACCES AU MENU DE CONFIGURATION

coils:
  c_flipper_left_main:
    number: 0-0-8
    default_pulse_ms: 15
    default_hold_power: 0.125
    allow_enable: true
  c_flipper_left_mini_main:
    number: 0-0-9
    default_pulse_ms: 10
    default_hold_power: 0.10
    allow_enable: true
  c_flipper_right_bas_main:
    number: 0-0-10
    default_pulse_ms: 12
    default_hold_power: 0.125
    allow_enable: true
  c_flipper_right_haut_main:
    number: 0-0-11
    default_pulse_ms: 10
    default_hold_power: 0.10
    allow_enable: true
  c_flipper_right_mini_main:
    number: 0-0-0
    default_pulse_ms: 10
    default_hold_power: 0.10
    allow_enable: true
  c_trough_eject:
    number: 0-0-12
    default_pulse_ms: 20
  c_plunger_eject:
    number: 0-0-13
    default_pulse_ms: 25
  c_left_slingshot:
    number: 0-0-14
    default_pulse_ms: 10
  c_right_slingshot:
    number: 0-0-15
    default_pulse_ms: 10
  c_lower_jet_bumper:
    number: 0-0-7
    default_pulse_ms: 10
  c_left_jet_bumper:
    number: 0-0-6
    default_pulse_ms: 10
  c_right_jet_bumper:
    number: 0-0-5
    default_pulse_ms: 10
  c_left_popper:
    number: 0-0-4
    default_pulse_ms: 20
  c_right_popper:
    number: 0-0-3
    default_pulse_ms: 20
  c_deviateur_bras_actuate:
    number: 0-0-2
    default_pulse_ms: 30
  c_top_popper:
    number: 0-0-1
    default_pulse_ms: 20
  c_eject_bras_virtual:
    number: 1
    platform: virtual
    default_pulse_ms: 20
  c_shaker:
    number: 1-0-0
    default_pulse_ms: 1
    default_hold_power: 0.125

autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_slingshot
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
  lower_jet:
    coil: c_lower_jet_bumper
    switch: s_lower_jet
  left_jet:
    coil: c_left_jet_bumper
    switch: s_left_jet
  right_jet:
    coil: c_right_jet_bumper
    switch: s_right_jet

diverters:
  deviateur_rampe_bras:
    activation_coil: c_deviateur_bras_actuate
    type: pulse
    activate_events: multiball_lock_lock_einstein_enabled
    disable_events: multiball_lock_lock_einstein_disabled

servos:
  servo_bras_einstein:
    number: 0-0-11
    reset_position: 0.2
    servo_min: 0.1
    servo_max: 0.9
    positions:
      0.2: position_de_repos_du_bras
      0.8: position_max_du_bras
    reset_events: reset_servo_bras_einstein
    debug: true

servo_controllers:
  controleur_bras_einstein:
    servo: servo_bras_einstein
    control_events:
      - event: start_multiball_einstein
        position: 0.8
      - event: c_eject_bras_virtual_pulsed
        position: 0.8
      - event: multiball_einstein_ended
        position: 0.2
      # - event: balldevice_bd_bras_rotatif_ball_ejected
        # position: 0.2

flippers:
  left_flipper_main:
    main_coil: c_flipper_left_main
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
  left_flipper_mini:
    main_coil: c_flipper_left_mini_main
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
  right_flipper_bas:
    main_coil: c_flipper_right_bas_main
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3
  right_flipper_haut:
    main_coil: c_flipper_right_haut_main
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3
  right_flipper_mini:
    main_coil: c_flipper_right_mini_main
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3

spinners:
  basic_spinner:
    switch: s_spinner_almanach
    #active_ms: 500
    switch: s_spinner_pierre_cardin
    #active_ms: 500

machine:
  balls_installed: 5
  min_balls: 5

game:
  balls_per_game: 5
  max_players: 4

virtual_platform_start_active_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    eject_timeouts: 3s
    entrance_count_delay: 300ms
    debug: true
  bd_plunger:
    ball_switches: s_plunger
    eject_timeouts: 5s
    entrance_count_delay: 300ms
    eject_coil: c_plunger_eject
    eject_targets: playfield
    player_controlled_eject_event: sw_launch #bouton d'action
    debug: true
  bd_left_vuk:
    ball_switches: s_left_popper
    eject_timeouts: 2s
    eject_coil: c_left_popper
    eject_targets: playfield
    debug: true
  bd_right_vuk:
    ball_switches: s_right_popper
    eject_timeouts: 2s
    eject_coil: c_right_popper
    eject_targets: playfield
    debug: true
  bd_upper_vuk:
    ball_switches: s_top_popper
    eject_timeouts: 2s
    eject_coil: c_top_popper
    eject_targets: bd_bras_rotatif
  bd_bras_rotatif:
    ball_switches: s_bras_slot1, s_bras_slot2, s_bras_slot3
    eject_coil: c_eject_bras_virtual
    eject_targets: playfield
    tags: lock
    debug: true
    
ball_holds:
  delorean:
    balls_to_hold: 1
    hold_devices: bd_left_vuk
    enable_events: shot_qualification_selection_modes_group_complete
    release_events: selection_modes_completed

playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default
    enable_ball_search: true

ball_saves:
  default_ball_save:
    active_time: 10s
    hurry_up_time: 2s
    grace_period: 1s
    enable_events: ball_started
    auto_launch: true
    early_ball_save_events: s_left_outlane_active, s_right_outlane_active #Compter les voies de sortie comme des drains pour accélérer la manipulation
    balls_to_save: -1 # unlimited saves

player_vars:
  potato:
    initial_value: 0
    
lights:
# VOIR CB POUR LE TRANSLITE
# VOIR CB POUR LE CONVECTEUR
# VOIR COMMENT GERER AMPOULE DES BUMPERS
# VOIR COMMENT GERER LED DE LA DELOREAN
# VOIR POUR LES 2 LAMPES SUR PIED
  l_translite_1:
    number: 0-0-53
  l_translite_2:
    number: 0-0-54
  l_translite_3:
    number: 0-0-55
  l_translite_4:
    number: 0-0-56
  l_translite_5:
    number: 0-0-57
  l_translite_6:
    number: 0-0-58
  l_translite_7:
    number: 0-0-59
  l_translite_8:
    number: 0-0-60
  l_translite_9:
    number: 0-0-61
  l_translite_10:
    number: 0-0-62
  l_translite_11:
    number: 0-0-63
  l_translite_12:
    number: 0-0-64
  l_translite_13:
    number: 0-0-65
  l_translite_14:
    number: 0-0-66
  l_translite_15:
    number: 0-0-67
  l_translite_16:
    number: 0-0-68
  l_translite_17:
    number: 0-0-69
  l_translite_18:
    number: 0-0-70
  l_translite_19:
    number: 0-0-71
  l_translite_20:
    number: 0-0-72
  l_translite_21:
    number: 0-0-73
  l_translite_22:
    number: 0-0-74
  l_translite_23:
    number: 0-0-75
  l_translite_24:
    number: 0-0-76
  l_translite_25:
    number: 0-0-77

  l_left_outlane:
    number: 0-0-0
  l_left_inlane_lower:
    number: 0-0-1
  l_left_inlane_top:
    number: 0-0-2
  l_left_slingshot_lower:
    number: 0-0-3
  l_left_slingshot_top:
    number: 0-0-4
  l_right_outlane:
    number: 0-0-5
  l_right_inlane_lower:
    number: 0-0-6
  l_right_inlane_top:
    number: 0-0-7
  l_right_slingshot_lower:
    number: 0-0-8
  l_right_slingshot_top:
    number: 0-0-9
    
  l_left_inter_lower:
    number: 0-0-10
  l_left_inter_top:
    number: 0-0-11
  l_right_inter_lower:
    number: 0-0-12
  l_right_inter_middle_lower:
    number: 0-0-13
  l_right_inter_middle_top:
    number: 0-0-14
  l_right_inter_top:
    number: 0-0-15
    
  l_left_top_lower:
    number: 0-0-16
  l_left_top_top:
    number: 0-0-17
  l_left_top_left:
    number: 0-0-18
  l_left_top_right:
    number: 0-0-19
  l_miniplayfield_lower:
    number: 0-0-20
  l_miniplayfield_top:
    number: 0-0-21
    
  l_up_middle:
    number: 0-0-22
  l_up_middle_left:
    number: 0-0-23
  l_up_left:
    number: 0-0-24
  l_up_middle_right:
    number: 0-0-25
  l_up_right:
    number: 0-0-26
  
  l_insert_shoot_again:
    number: 1-0-0
  l_insert_left_inlane:
    number: 1-0-1
  l_insert_left_outlane:
    number: 1-0-2
  l_insert_right_inlane:
    number: 1-0-3
  l_insert_right_outlane:
    number: 1-0-4
    
  l_insert_1885:
    number: 1-0-5
  l_insert_1955:
    number: 1-0-6
  l_insert_1985:
    number: 1-0-7
  l_insert_2015:
    number: 1-0-8
  l_insert_biff:
    number: 1-0-9
  l_insert_bttf:
    number: 1-0-10
  l_insert_x2:
    number: 1-0-11
  l_insert_extraball:
    number: 1-0-12
  
  l_entree_souterrain:
    number: 0-0-27
  l_delorean:
    number: 0-0-28
  l_insert_delorean_left_1:
    number: 1-0-13
  l_insert_delorean_left_2:
    number: 1-0-14
  l_insert_delorean_left_3:
    number: 1-0-15
  l_insert_delorean_left_4:
    number: 1-0-16
  l_insert_delorean_right_1:
    number: 1-0-17
  l_insert_delorean_right_2:
    number: 1-0-18
  l_insert_delorean_right_3:
    number: 1-0-19
  l_insert_delorean_right_4:
    number: 1-0-20
  
  l_lower_jet_1:
    number: 0-0-29
  l_lower_jet_2:
    number: 0-0-30
  l_lower_jet_3:
    number: 0-0-31
  l_lower_jet_4:
    number: 0-0-32
  l_lower_jet_lower:
    number: 0-0-33
  l_lower_jet:
    number: 0-0-34
  l_left_jet_1:
    number: 0-0-35
  l_left_jet_2:
    number: 0-0-36
  l_left_jet_3:
    number: 0-0-37
  l_left_jet_4:
    number: 0-0-38
  l_left_jet_lower:
    number: 0-0-39
  l_left_jet:
    number: 0-0-40
  l_right_jet_1:
    number: 0-0-41
  l_right_jet_2:
    number: 0-0-42
  l_right_jet_3:
    number: 0-0-43
  l_right_jet_4:
    number: 0-0-44
  l_right_jet_lower:
    number: 0-0-45
  l_right_jet:
    number: 0-0-46
    
  # OPTOS
  l_ramp_1985_entree:
  # PK ENTREE ???
    number: 0-0-47
  l_insert_ramp_hotel_de_ville:
    number: 1-0-21
  l_ramp_2015_lower:
    number: 0-0-48
    
  l_insert_ramp_george:
    number: 1-0-22
  l_insert_ramp_bttf:
    number: 1-0-23
    
  l_insert_target_plutonium:
    number: 1-0-24
  l_insert_lane_1955:
    number: 1-0-25
  l_left_popper:
    number: 0-0-49
  l_insert_bank_dmc_lower:
    number: 1-0-26
  l_insert_bank_dmc_middle:
    number: 1-0-27
  l_insert_bank_dmc_upper:
    number: 1-0-28
  l_insert_entree_souterrain:
    number: 1-0-29
  
  l_insert_ramp_1955:
    number: 1-0-30
  l_insert_lane_1885:
    number: 1-0-31
  l_right_popper:
    number: 0-0-50
  
  l_insert_target_hill_valley:
    number: 1-0-32
  l_insert_lane_cafe_einstein:
    number: 1-0-33
  l_insert_lane_einstein_upper:
    number: 1-0-34
  l_insert_einstein_multiball:
    number: 1-0-35
 
  l_insert_lane_biff:
    number: 1-0-36
  l_insert_lane_doc_lower:
    number: 1-0-37
  l_insert_lane_doc_upper:
    number: 1-0-38
  l_insert_lane_horloge:
    number: 1-0-39
  l_insert_target_foudre:
    number: 1-0-40
  l_insert_target_overboard:
    number: 1-0-41
  l_insert_bank_doc_lower:
    number: 1-0-42
  l_insert_bank_doc_middle:
    number: 1-0-43
  l_insert_bank_doc_upper:
    number: 1-0-44
  l_insert_ramp_2015_upper:
    number: 1-0-45
  l_insert_lane_marty:
    number: 1-0-46
  l_insert_lane_lorraine:
    number: 1-0-47
  l_insert_lane_marvin:
    number: 1-0-48
    
  l_insert_lane_guitar_1:
    number: 1-0-49
  l_insert_lane_guitar_2:
    number: 1-0-50
  l_insert_lane_guitar_3:
    number: 1-0-51
  l_insert_lane_guitar_4:
    number: 1-0-52
  l_insert_lane_guitar_5:
    number: 1-0-53
  l_insert_lane_guitar_6:
    number: 1-0-54
  l_insert_lane_guitar_7:
    number: 1-0-55
  l_insert_lane_guitar_8:
    number: 1-0-56
  l_insert_lane_guitar_9:
    number: 1-0-57
  l_insert_lane_guitar_10:
    number: 1-0-58
    
  l_start_button:
    number: 0-0-51
  l_launch_button:
    number: 0-0-52