#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

#CobraPin

modes:
  - attract
  # ATTRACT. C'est le mode "sommeil" du flipper quand personne ne joue.
  # Il gère le défilement des lumières sur le plateau,
  # l'affichage sur l'écran qui dit "Appuyez sur Start",
  # et attend que le joueur lance une partie.
  - base
  # BASE. Dès qu'un joueur appuie sur Start, le mode attract s'arrête et le mode base se lance.
  # C'est lui qui gère le déroulement d'une partie classique.

hardware:
  platform: opp

opp:
  ports: COM

psus:
  default:
    #Gives the capacitors extra time to recharge after firing a coil
    #  and eases the load on the power supply. Doesn't affect autofire
    #  devices like flippers, pops, slings.
    release_wait_ms: 50

switches:
  s_left_flipper:
    number: 0-0-1
    tags: left_flipper
  s_right_flipper:
    number: 0-0-2
    tags: right_flipper

  s_start:
    number: 0-0-3
    tags: start

  s_trough1:
    number: 0-0-9
  s_trough2:
    number: 0-0-10
  s_trough3:
    number: 0-0-11
  s_trough4:
    number: 0-0-27
  s_trough_jam:
    number: 0-0-8
  s_plunger:
    number: 0-0-26

  s_right_outlane:
    number: 0-0-25
    tags: playfield_active
  s_right_inlane:
    number: 0-0-24
    tags: playfield_active
  s_left_inlane:
    number: 0-0-19
    tags: playfield_active
  s_left_outlane:
    number: 0-0-18
    tags: playfield_active

coils:
  # === CÔTÉ GAUCHE ===
  c_flipper_left_main:
    number: 0-0-8
    default_pulse_ms: 15
    default_hold_power: 0.125
    allow_enable: true        # Autorise le maintien par PWM

  c_flipper_left_mini_main:
    number: 0-0-9
    default_pulse_ms: 10
    default_hold_power: 0.10
    allow_enable: true

  # === CÔTÉ DROIT ===
  c_flipper_right_bas_main:
    number: 0-0-10
    default_pulse_ms: 12
    default_hold_power: 0.125
    allow_enable: true

  c_flipper_right_haut_main:
    number: 0-0-11
    default_pulse_ms: 10
    default_hold_power: 0.10
    allow_enable: true

  c_flipper_right_mini_main:
    number: 0-0-0
    default_pulse_ms: 10
    default_hold_power: 0.10
    allow_enable: true

  c_trough_eject:
    number: 0-0-12
    default_pulse_ms: 20

flippers:
  # === CONFIGURATION GAUCHE ===
  left_flipper_main:
    main_coil: c_flipper_left_main
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3

  left_flipper_mini:
    main_coil: c_flipper_left_mini_main
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3

  # === CONFIGURATION DROITE ===
  right_flipper_bas:
    main_coil: c_flipper_right_bas_main
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3

  right_flipper_haut:
    main_coil: c_flipper_right_haut_main
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3

  right_flipper_mini:
    main_coil: c_flipper_right_mini_main
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3

machine:
  balls_installed: 5 #How many balls are physically in your game
  min_balls: 5 #How few balls can be accounted for before you can start a game

game:
  balls_per_game: 5
  max_players: 4

displays:
  window:
    width: 1920
    height: 1080
    fps: 75

virtual_platform_start_active_switches: s_trough1, s_trough2, s_trough3, s_trough4

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    eject_timeouts: 3s
  bd_plunger:
    ball_switches: s_plunger
    mechanical_eject: true
    eject_timeouts: 5s

playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default

