#config_version=6

mode:
  start_events: ball_started
  priority: 500

# 1. Compteur de tirs standard
counters:
  compteur_tirs_einstein:
    count_events: s_lane_cafe_einstein_active
    count_complete_value: 12                     # Valeur max finale pour la logique
    persist_state: true
    reset_on_complete: false                    # On ne reset pas pour pouvoir monter à 6, 9, 12

# 2. Gestion dynamique de la progression des paliers et des actions de sécurité
event_player:
  # Déclenchement du déviateur aux paliers 3, 6, 9, 12
  # Note : On utilise la valeur du compteur comme condition directe
  compteur_tirs_einstein_value{value==3}:
    - activer_deviateur_einstein
  compteur_tirs_einstein_value{value==6}:
    - activer_deviateur_einstein
  compteur_tirs_einstein_value{value==9}:
    - activer_deviateur_einstein
  compteur_tirs_einstein_value{value==12}:
    - activer_deviateur_einstein
  
  # Sécurités du déviateur déplacées ici sous forme d'événements standards
  multiball_lock_lock_einstein_full: desactiver_deviateur_bras
  mode_multiball_einstein_started: desactiver_deviateur_bras

# 3. Logique de verrouillage physique pour les 3 slots
multiball_locks:
  lock_einstein:
    lock_devices: bd_bras_rotatif
    balls_to_lock: 3

# 4. Déclenchement de la multibille à 3 billes
multiballs:
  multiball_einstein:
    ball_count: 3
    ball_locks: bd_bras_rotatif                 
    start_events: multiball_lock_lock_einstein_full