#config_version=6

mode:
  start_events: ball_started
  priority: 500

slides:
  slide_einstein_multiball:
    target: DefaultDisplay
    # - type: scene
      # scene: einstein_multiball_video  # MPF va chercher "einstein_multiball_video.tscn" dans vos slides/

# 1. Compteur étendu (la valeur max s'adapte ou monte haut pour laisser tourner)
counters:
  compteur_tirs_einstein:
    count_events: s_lane_cafe_einstein_active
    count_complete_value: 100                    # Valeur plafond haute pour laisser le compteur évoluer
    persist_state: true
    reset_on_complete: false

# 2. Gestion de la progression et des déclenchements
event_player:
  # Paliers 3, 9, 18, 30
  compteur_tirs_einstein_value{value==3}:
    - activer_deviateur_einstein
    - declencher_einstein_multiball
    - slide_einstein_multiball
  compteur_tirs_einstein_value{value==9}:
    - activer_deviateur_einstein
    - declencher_einstein_multiball
    - slide_einstein_multiball
  compteur_tirs_einstein_value{value==18}:
    - activer_deviateur_einstein
    - declencher_einstein_multiball
    - slide_einstein_multiball
  compteur_tirs_einstein_value{value==30}:
    - activer_deviateur_einstein
    - declencher_einstein_multiball
    - slide_einstein_multiball
  
  # Paliers continus toutes les 12 après 30
  compteur_tirs_einstein_value{value >= 42 and (value - 30) % 12 == 0}:
    - activer_deviateur_einstein
    - declencher_einstein_multiball
    - slide_einstein_multiball
  
  # Sécurités du déviateur
  multiball_lock_lock_einstein_full: desactiver_deviateur_bras
  mode_einstein_multiball_started: desactiver_deviateur_bras

# 3. Logique de verrouillage physique
multiball_locks:
  lock_einstein:
    lock_devices: bd_bras_rotatif
    balls_to_lock: 3

# 4. Déclenchement de la multibille
multiballs:
  einstein_multiball:
    ball_count: 3
    ball_locks: bd_bras_rotatif                 
    start_events: declencher_einstein_multiball