#config_version=6

mode:
  start_events: qualification_selection_modes_group_complete
  priority: 500

variable_player:
  mode_selection_modes_started{current_player.current_year == none}:
    current_year: 1985

  s_flipper_left_active{current_player.current_year == 1985}:
    current_year: 1955
  s_flipper_left_active{current_player.current_year == 1955}:
    current_year: 1885
  s_flipper_left_active{current_player.current_year == 1885}:
    current_year: 2015
  s_flipper_left_active{current_player.current_year == 2015}:
    current_year: 1985

  s_flipper_right_active{current_player.current_year == 1985}:
    current_year: 2015
  s_flipper_right_active{current_player.current_year == 2015}:
    current_year: 1885
  s_flipper_right_active{current_player.current_year == 1885}:
    current_year: 1955
  s_flipper_right_active{current_player.current_year == 1955}:
    current_year: 1985

light_player:
  s_flipper_left_active{current_player.current_year == 1885}, s_flipper_right_active{current_player.current_year == 1885}, mode_selection_modes_started{current_player.current_year == 1885}:
    l_insert_1885: white
    l_insert_1955: off
    l_insert_1985: off
    l_insert_2015: off

  s_flipper_left_active{current_player.current_year == 1955}, s_flipper_right_active{current_player.current_year == 1955}, mode_selection_modes_started{current_player.current_year == 1955}:
    l_insert_1885: off
    l_insert_1955: white
    l_insert_1985: off
    l_insert_2015: off

  s_flipper_left_active{current_player.current_year == 1985}, s_flipper_right_active{current_player.current_year == 1985}, mode_selection_modes_started{current_player.current_year == 1985}:
    l_insert_1885: off
    l_insert_1955: off
    l_insert_1985: white
    l_insert_2015: off

  s_flipper_left_active{current_player.current_year == 2015}, s_flipper_right_active{current_player.current_year == 2015}, mode_selection_modes_started{current_player.current_year == 2015}:
    l_insert_1885: off
    l_insert_1955: off
    l_insert_1985: off
    l_insert_2015: white

  s_left_popper_active:
    l_launch_button: orange

  s_launch_active:
    l_insert_year: off
    l_launch_button: off

show_player:
  qualification_selection_modes_group_complete:
    base_year:
      action: play
      loops: -1
  s_left_popper_active:
    base_year:
      action: play
      loops: -1
      # Correction de "tokens" en "show_tokens"
      show_tokens:
        light: l_launch_button
  s_launch_active:
    base_year:
      action: stop

slide_player:
  mode_selection_modes_started:
    slide_choix_epoque:
      action: play

event_player:
  s_launch_active:
    - start_mode_{current_player.current_year}
    - selection_completed
    - bd_left_vuk_eject
    - stop_mode