#config_version=6

variable_player:
  # Lorsque le mode 1985 se termine et est complété avec succès :
  mode_1955_success:
    year_1955_completed: 1
    
variable_player:
  mode_1955_started:
    year_1955_started: 1
  mode_1955_success:
    year_1955_completed: 1